package org.vaadin.example;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g
 * class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DashboardViewDesign extends CssLayout {
    protected Label billing_header_label;
    protected CssLayout dashboard_item5;
    protected Label dashboard_item_header;
    protected Label statistics_label;
    protected Label statistics_label2;
    protected Label statistics_label4;
    protected Label statistics_label3;
    protected Label statistics_label5;
    protected CssLayout dashboard_item26;
    protected Label dashboard_item_header2;
    protected Label statistics_label6;
    protected Label statistics_label7;
    protected Label statistics_label8;
    protected Label statistics_label9;
    protected Label statistics_label10;
    protected CssLayout dashboard_item27;
    protected Label dashboard_item_header3;
    protected Label statistics_label18;
    protected Label statistics_label12;
    protected Label statistics_label16;
    protected Label statistics_label17;

    public DashboardViewDesign() {
        Design.read(this);
    }
}
